# Generated by Django 2.1.7 on 2019-03-12 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliverGoods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DeliverGoods.GoodsCategory', verbose_name='商品类型'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='goods',
            field=models.ManyToManyField(to='DeliverGoods.Goods', verbose_name='商品'),
        ),
    ]
